spring:

  application:
    name: demo

  datasource:
    url: jdbc:postgresql://localhost:26257/defaultdb?sslmode=disable
    username: root
    password: ""
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 50
      minimum-idle: 20

  liquibase:
    change-log: classpath:db/db.changelog-master.yaml
    enabled: true

springdoc:
  # Set the default response type to JSON, required by the React client
  default-produces-media-type: application/json