@startuml

title Signed upload (the media processing logic is skipped)

skinparam BoxPadding 5
skinparam ParticipantPadding 5

actor Client

box Main
participant MainApp
database MainDB
endbox

box Media
participant MediaApp
endbox

group requesting upload
Client->MainApp: file metadata, upload category
MainApp->MainApp: can this user create a new upload?
MainApp->MainApp: is the upload metadata good for this category?
MainApp->MainApp: get the upload preset name of this category
MainApp->MainDB: store the pending upload
note over MainDB: upload key, category, date, pending status
return unique upload key
MainApp->MainApp: create signed upload token with the upload id and preset name
MainApp-->Client: upload parameters + signature
end

group uploading
Client->MediaApp: upload parameters + signature + file
note over MediaApp: *validation, registration, transformations, object storage*
group webhook
MediaApp->MainApp: upload identity and metadata
MainApp->MainDB: update the status of the upload key to ready
end
MediaApp-->Client: upload identity and metadata
end

group submit post
Client->MainApp: post parameters, upload keys
MainApp->MainApp: validate post and uploads
MainApp->MainDB: insert the post
return post id
MainApp->MainDB: insert upload links between the post and uploads
note over MainDB: post id, upload key
note over MainDB: should the upload record status be updated from "ready" to "linked"?
MainApp-->Client: post id
end

@enduml